### ISSUE TITLE
AWS Athena query support

### ISSUE THREAD

**Issue by adamist521** [prestodb-rocks/presto-query-formatter#7]
Not sure whether this is certain place to ask but I was looking for Presto (AWS athena query) formatter and came up here.
Would it be possible to support Athena query or do they use dialect so it wouldn't be supported here?

I already faced three error on parsing...  I'll put error messages below.

1.  `CREATE EXTERNAL` when I tried to create external table
```
$ cat sample.sql | presto-query-formatter-0.2-executable.jar > formatted.sql
Exception in thread "main" com.facebook.presto.sql.parser.ParsingException: line 1:8: no viable alternative at input 'CREATE EXTERNAL'
	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:45)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:284)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:121)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:2638)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:236)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:92)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:65)
	at rocks.prestodb.query.formatter.Main.format(Main.java:61)
	at rocks.prestodb.query.formatter.Main.main(Main.java:42)
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2025)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1376)
```

2. `` ` ``  backtick
```
$ cat sample.sql | presto-query-formatter-0.2-executable.jar > formatted.sql
Exception in thread "main" com.facebook.presto.sql.parser.ParsingException: line 2:9: backquoted identifiers are not supported; use double quotes to quote identifiers
	at com.facebook.presto.sql.parser.SqlParser$PostProcessor.exitBackQuotedIdentifier(SqlParser.java:133)
	at com.facebook.presto.sql.parser.SqlBaseParser$BackQuotedIdentifierContext.exitRule(SqlBaseParser.java:10605)
	at org.antlr.v4.runtime.Parser.triggerExitRuleEvent(Parser.java:404)
	at org.antlr.v4.runtime.Parser.exitRule(Parser.java:620)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:247)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:92)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:65)
	at rocks.prestodb.query.formatter.Main.format(Main.java:61)
	at rocks.prestodb.query.formatter.Main.main(Main.java:42)
```

3. `struct` after `<`
```
$ cat sample.sql | presto-query-formatter-0.2-executable.jar > formatted.sql
Exception in thread "main" com.facebook.presto.sql.parser.ParsingException: line 4:29: mismatched input '<' expecting {'(', 'ARRAY', '>'}
	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:45)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:301)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:124)
	at com.facebook.presto.sql.parser.SqlBaseParser.type(SqlBaseParser.java:9038)
	at com.facebook.presto.sql.parser.SqlBaseParser.type(SqlBaseParser.java:8921)
	at com.facebook.presto.sql.parser.SqlBaseParser.columnDefinition(SqlBaseParser.java:2987)
	at com.facebook.presto.sql.parser.SqlBaseParser.tableElement(SqlBaseParser.java:2922)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1638)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:236)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:92)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:65)
	at rocks.prestodb.query.formatter.Main.format(Main.java:61)
	at rocks.prestodb.query.formatter.Main.main(Main.java:42)
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:244)
	at com.facebook.presto.sql.parser.SqlBaseParser.type(SqlBaseParser.java:8979)
	... 9 more
```

**Comment by kokosing** [comment]
> Not sure whether this is certain place to ask but I was looking for Presto (AWS athena query) formatter and came up here.
Would it be possible to support Athena query or do they use dialect so it wouldn't be supported here?

It is good place. This formatter should support that, however it was updated for a long time so it may fail on things that were added during that time.

> 1. CREATE EXTERNAL

It looks like HiveQL which is not supported by Presto.

> 2. ` backtick

backticks are also not supported by Presto. Presto tries to follow the ANSI SQL standard as much as possible. Using backticks is very hive specific.

> 3. struct after <

Please do not support such syntax, see https://docs.starburstdata.com/latest/language/types.html#structural

**Comment by kokosing** [comment]
@adamist521 I was not aware that AWS Athena SQL is a modified version Presto SQL. This formatter only supports vanilla Presto SQL.

**Comment by adamist521** [comment]
@kokosing
Thank you for your reply!

Reading carefully inside the FAQ, figured out that Athena uses Apache Hive DDL for table creation and uses Presto for quering.
Was trying format Hive... 

https://aws.amazon.com/athena/faqs/
